<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <div>
    <label><?php echo $this->__('Transction No') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Transction No') ?>" name="payment[transction_no]" value="<?php echo $this->htmlEscape($this->getInfoData('transction_no')) ?>" />
    </span>
  </div>
  <div>
    <label><?php echo $this->__('Payment Method') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Payment Method') ?>" name="payment[payment_method]" value="<?php echo $this->htmlEscape($this->getInfoData('payment_method')) ?>" />
    </span>
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>